Repository SmartCambridge/tfc_web, pull requests merged in 2018-08, with the labels that each got.

#185 Smartpanels: Import/Export functionality
  tfc_web/smartpanel/templates/smartpanel/layout_config.html
  tfc_web/smartpanel/templates/smartpanel/my.html
  tfc_web/smartpanel/urls.py
  tfc_web/smartpanel/views/smartpanel.py
  tfc_web/static/style.css
Labels: SmartPanels

#202 Implement a new bikes sharing widget
  README.md
  tfc_web/Dockerfile
  tfc_web/requirements.txt
  tfc_web/smartpanel/urls.py
  tfc_web/smartpanel/views/smartpanel.py
  tfc_web/smartpanel/views/widgets/bikes.py
  tfc_web/static/smartpanel/widgets/bikes/bikes.css
  tfc_web/static/smartpanel/widgets/bikes/bikes.js
  tfc_web/static/smartpanel/widgets/bikes/bikes_schema.json
  tfc_web/static/smartpanel/widgets/bikes/images/mobike_red.png
  tfc_web/static/smartpanel/widgets/bikes/images/mobike_white.png
  tfc_web/static/smartpanel/widgets/bikes/images/ofo.png
  tfc_web/static/smartpanel/widgets/bikes/requirements.json
Labels: SmartPanels, enhancement

#181 Replace api/dataserver with api/
  README.md
  scripts/insert_tfc_web_internal_token
  tfc_web/api/tests/data/README_test_data.md
  tfc_web/api/tests/data/cam_park_local/data_monitor_json/post_data.json
  tfc_web/api/tests/data/cam_park_local/data_monitor_json/post_data.json.prev
  tfc_web/api/tests/data/cam_park_rss/data_monitor_json/post_data.json
  tfc_web/api/tests/data/cam_park_rss/data_monitor_json/post_data.json.prev
  tfc_web/api/util.py
  tfc_web/aq/views.py
  tfc_web/parking/templates/parking/parking_plot.html
  tfc_web/parking/views.py
  tfc_web/static/images/zone-icon.png
  tfc_web/static/images/zone_list_640x426.png
  tfc_web/tfc_web/settings.py
  tfc_web/tfc_web/settings_dev.py
  tfc_web/tfc_web/settings_devijl.py
  tfc_web/tfc_web/settings_production.py
  tfc_web/traffic/templates/traffic/home.html
  tfc_web/traffic/templates/traffic/zone_map.html
  tfc_web/traffic/templates/traffic/zone_transit_plot.html
  tfc_web/traffic/templates/traffic/zones_list.html
  tfc_web/traffic/templates/traffic/zones_map.html
  tfc_web/traffic/urls.py
  tfc_web/traffic/views.py
  tfc_web/traffic/views.py~
Labels: API
